### ISSUE TITLE
Add latest promise to PrepareReq

### ISSUE THREAD

**Issue by haraldng** [haraldng/omnipaxos#118]
Add a new field `last_promise: Ballot` in the `PrepareReq` message so that a stale leader can simply ignore it if the `last_promise` is greater than its current ballot.

**Comment by kevin-harrison** [comment]
Nodes send `PrepareReq`s to the `pid` of their current leader, meaning at one point it was promised to this `pid`. So even if the promise is to a stale leader this stale leaders ballot will be >= the follower's promise. One edge case is when the stale leader crashes and recovers (technically the leader_state ballot is recovered as well but we don't use it). When the leader recovers it will be in (Follower, Recover) state and will ignore the `PrepareReq`.

**Comment by haraldng** [comment]
In fact, the nodes don't just send PrepareReq to the node they were promised to, but to all peers if they recover from a crash.

I know that the Prepare sent by the stale leader will be ignored if the node already has a higher promise. The point is that it is unnecessary in the first place to send the Prepare, which could be avoided if the PrepareReq contained the promised ballot.

The case you're talking about is not an edge case. If a leader crashes and recovers, it won't continue to lead with the ballot it had before crashing. So ignoring the PrepareReq during recovery is correct.

**Comment by kevin-harrison** [comment]
How do you feel about not sending `PrepareReq`s on crash-recovery? They cause unnecessary resync if no message was lost during the downtime, and if a message was lost the follower will send the request once it receives any message from the leader.

**Comment by haraldng** [comment]
I still prefer sending PrepareReq on recovery. We don't know how often a message is sent i.e., how high timeout the users set or how often an entry will get proposed. So I prefer the node catching up as soon as possible after recovery. I don't think resyncing unnecessary is a big deal since the node must anyway go through prepare and promise.

**Comment by haraldng** [comment]
Fixed in #117
