### ISSUE TITLE
Iconsistent indexes

### ISSUE THREAD

**Issue by arejula27** [haraldng/omnipaxos#134]
# Issue Description:
Using the Omnipaxos structure, I realized that the indexes returned are inconsistent. If the omnipaxos history is empty, it returns the index 0, and when the first element is added, it returns the index 1. This can be demonstrated using the example/kv_store code. I have added a test in my local project.
```
fn test_indexes() {
    let runtime = Builder::new_multi_thread()
        .worker_threads(4)
        .enable_all()
        .build()
        .unwrap();
////////
//Initialize the systems as the main function
//////
  
    // wait for leader to be elected...
    std::thread::sleep(WAIT_LEADER_TIMEOUT);
    let (first_server, _) = op_server_handles.get(&1).unwrap();
    // check which server is the current leader
    let leader = first_server
        .lock()
        .unwrap()
        .get_current_leader()
        .expect("Failed to get leader");
    println!("Elected leader: {}", leader);
    let (leader_server, leader_join_handle) = op_server_handles.get(&leader).unwrap();

    //CHECK EMPTY DECIDED INDEX;SHOULD BE 0
    ///////////////////////////////////////
    let empty_idx = leader_server.lock().unwrap().get_decided_idx();

    //ADD ENTRY
    ///////////////////////////////////////
    assert!(empty_idx == 0);
    let kv2 = KeyValue {
        key: "b".to_string(),
        value: 2,
    };
    println!("Adding value: {:?} via server {}", kv2, leader);
    leader_server
        .lock()
        .unwrap()
        .append(kv2)
        .expect("append failed");
    // wait for the entries to be decided...
    std::thread::sleep(WAIT_DECIDED_TIMEOUT);

    //CHECK FIRST ENTRY DECIDED INDEX;SHOULD BE 1
    ///////////////////////////////////////
    let first_idx = leader_server.lock().unwrap().get_decided_idx();
    assert!(first_idx == 1);
```
However, these indexes are different when retrieving data. If you retrieve from the decided index 0, it returns all entries from the history, but if you retrieve from 1, it skips the first one:
```
    //READ DECIDED ENTRIES FROM 0, SHOULD BE SIZE 1
    ///////////////////////////////////////
  let committed_ents = leader_server
        .lock()
        .unwrap()
        .read_decided_suffix(0)
        .expect("Failed to read expected entries");
    assert!(committed_ents.len() == 1);

    //READ DECIDED ENTRIES FROM 1, SHOULD BE NONE
    ///////////////////////////////////////
    let committed_ents = leader_server.lock().unwrap().read_decided_suffix(1);

    assert!(committed_ents.is_none());
```
# Solution 1
I would propose to make them coherent. As this is an abstraction for people who may not understand Omnipaxos, the interface should be similar to most collections in software development, where the first index is 0. This implies that if the log is empty, the returned value from get_decided_idx should be None (change the type from `u64` to `Option<u64>`).

# Solution 2
If this inconsistency is based on the internal implementation or must be done this way because it is how the algorithm works, I suggest detailing it in the [documentation](https://docs.rs/omnipaxos/latest/omnipaxos/). Explicitly stating that using `read_decided_suffix does` not include the first index and explaining that index 0 means empty history should be sufficient clarification. This helps users understand the behaviour and adapt their code accordingly.

**Comment by haraldng** [comment]
I understand that this could be confusing, but the indexing follows how the indexing is done in Rust's standard `Vec` API where `len()` returns how many items exists i.e., 0 means empty, and `get(i)`accesses the item at index `i`.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=93e8b371467bfc6091b046ba421798d7

**Comment by haraldng** [comment]
I could see the argument that len() might not intuitvely correspond to the same API as get_decided_idx(). I'll update the docs!

**Comment by arejula27** [comment]
Is it intended for `read_decided_suffix(1)` to return an empty vector (with no elements) when `get_decided_idx` returns 1 with only one element?
I'm not particularly concerned about the length of the vector, regardless of how the different indexes returnedare handled by `omnipaxos`

**Comment by haraldng** [comment]
Yes, read_decided_suffix(1) should return None because 1 is out of bounds if we only have one element (on index 0).

**Comment by arejula27** [comment]
> I understand that this could be confusing, but the indexing follows how the indexing is done in Rust's standard `Vec` API where `len()` returns how many items exists i.e., 0 means empty, and `get(i)`accesses the item at index `i`.
> 
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=93e8b371467bfc6091b046ba421798d7

In that case, renaming the function `get_decided_idx` to `get_decided_suffix_size` to align with Rust's standard, it's a valid suggestion for consistency. If the word 'index' is in the name, 0 would typically denote the first one. Renaming the function could indeed help in aligning the naming conventions with Rust's standards.

**Comment by haraldng** [comment]
I would avoid the word "suffix" for this function because it refers to a part of the log that should also depend on an index argument (i.e., suffix from index i). But I will consider `get_decided_len()`, which would maybe be better than `get_decided_idx()`.

Naming is hard :)

**Comment by arejula27** [comment]
100% Agree :D 
Thank you for taking my suggestion into consideration
