### ISSUE TITLE
Create Builder for SequencePaxos and BLE from configs

### ISSUE THREAD

**Issue by haraldng** [haraldng/omnipaxos#50]
Have a `build()` function in `SequencePaxosConfig` that does some basic asserts e.g. pid != 0 and returns `SequencePaxos`. Same for BLE.

**Comment by AbyelT** [comment]
Added `build()` functions for SequencePaxos & BLE configs in this commit https://github.com/haraldng/omnipaxos/pull/48/commits/ade26017557aa6bec27d13b404174262ad265ab0
