### ISSUE TITLE
broken tests

### ISSUE THREAD

**Issue by Max-Meldrum** [haraldng/omnipaxos#64]
Running tests for ``omnipaxos_core`` fails as it cannot find ``TestConfig``, which is only available using the ``hocon_config`` feature.

A quick fix would be to add ``hocon_config`` as a default feature. Although perhaps a better option, in the long run, is to eliminate the reliance on hocon in ``tests/``.

**Comment by haraldng** [comment]
I agree, we should remove the hocon dependency in the tests.

**Comment by Bathtor** [comment]
In general, the hocon library is no longer maintained as I recently discovered, so it would be good to try and migrate away from it. I got a ticket on the Kompact side to look into alternatives. See https://github.com/kompics/kompact/issues/187
