### ISSUE TITLE
[Request] Please add link to the Omni-Paxos Paper.

### ISSUE THREAD

**Issue by utkarsh-pro** [haraldng/omnipaxos#90]
Hi, omni-paxos looks extremely interesting and it is hard to hold back the curiosity now. Can you please add the link to the Omni-Paxos paper?

It might be possible that somewhere it is already present and I just cannot find it, if that's the case then please point me to it.

Thank you.

**Comment by haraldng** [comment]
Thanks for showing interest! The README is now updated with a link to the [paper](https://dl.acm.org/doi/pdf/10.1145/3552326.3587441).

Note that the publishers have some issues with Figure 2 and the artifact badge, but they should be resolved soon!
