### ISSUE TITLE
Implicitly decided stopsign during prepare phase

### ISSUE THREAD

**Issue by JonathanArns** [haraldng/omnipaxos#96]
The `Promise` and `AcceptSync` messages both contain a stopsign and the decided index. However the stopsign is never treated as decided in these messages. Unfortunately the decided index could still imply that the stopsign should be decided and this would also be reflected in storage, if the message is handled without errors.

It is not clear to me if this is a critical bug or just a quirk of the implementation, but it should be fixed.

In my opinion, the real issue here is that the storage API defines 2 values that indicate if a stopsign is decided or not (decided index, stopsign entry). This means there is no single source of truth on whether a stopsign is decided. This should only be in one value that will be the ground truth on this. If the API should still reflect this information in both values, this should be generated from that ground truth, most likely in internal storage.

**Comment by haraldng** [comment]
Indeed, I think one way to solve this is to replace the `decided` flag in the `StopSign` with its corresponding log index. Then the `decided_idx` is always the single source of truth.

**Comment by JonathanArns** [comment]
That sounds good, then the `Promise` and `AcceptSync` messages should probably also contain the full `StopsignEntry` or at least the index, not just the stopsign and then we can correctly sync decided stopsigns in the prepare phase. I think we could even get rid of the `AcceptedStopsign` message that is always sent after `AcceptSync` in that case.
