### ISSUE TITLE
Proposal: support truly atomic storage implementations

### ISSUE THREAD

**Issue by JonathanArns** [haraldng/omnipaxos#97]
This is a proposal for a big breaking change to the storage API.

Even after merging the most recent atomic storage PR, my biggest gripe with the current implementation of Omnipaxos is the storage API and its lack of support for atomic transactions. Because the current API only allows writing individual values one at a time, we cannot really change multiple values atomically, even if the underlying storage implementation could support it.

The rollbacks we do now are a nice addition on top of the current API, but they only deal with individual errors from within storage. If an error occurs somewhere else and the application crashes for example, these rollbacks cannot help us.

I think we need a big change to the writing part of the storage API. My proposal is to replace all write functions on the API with one single function that takes a set of changes and atomically applies them. This could look something like this:
```rust
pub enum StorageUpdate {
    DecidedIdx(u64),
    AppendOnPrefix(Vec<Entry>, u64),
    ...
}

pub trait storage {
    // reading functions are unchanged
    ...
    /// Should perform all of the updates as an atomic set of changes
    fn update(Vec<StorageUpdate>) -> StorageResult<()>;
    ...
}
```
Implementing this API would not be significantly more complicated than the current one (provided one is familiar with enums and pattern matching in rust). It would easily support an implementation very similar to the current ones, where values are individually written to the underlying storage mechanism, but it does not enforce this anymore. Instead the storage implementation could also make use of the transaction mechanism of an embedded DB, to build a much more robust system than is currently possible.

Another plus is that we could remove all of the rollback code in omnipaxos, because this responsibility will be put on the storage implementation. (Omnipaxos is really complicated enough without this logic as well)

**Comment by haraldng** [comment]
This would indeed be much nicer as it can take advantage of storage implementations that support transactions and keep the omnipaxos code clean. To further support storage implementations that are not atomic/don't support transactions we can create our own struct `AtomicStorage<L, S>` that implements this `Storage` trait and does what we did in #81, where the two generic parameters `L: LogTrait` and `S: StateTrait` do not need to implement any atomic operations.

In this way, users can either implement `Storage` directly if they have an implementation (e.g., a database) that supports transactions, or they can use our provided `AtomicStorage` with implementations that do not support transactions.
